[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Bodhi_worm_eart
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Bodhi_worm_eart
GtkTheme=oomox-Bodhi_worm_eart
IconTheme=oomox-Bodhi_worm_eart
MetacityTheme=oomox-Bodhi_worm_eart
